### ISSUE TITLE
Modes A and B

### ISSUE THREAD

**Issue by borjaapaolaza** [lseman/pylspm#2]
What do indicators-LV relation modes A and B stand for? It would be great if you could add it in the documentation ;-)

Thanks!

**Comment by lseman** [comment]
For modes A and B please refer to:

http://gastonsanchez.com/PLS_Path_Modeling_with_R.pdf

Laio O. Seman

**Comment by borjaapaolaza** [comment]
Thank you! It would be great if you added this info in the Wiki.
