### ISSUE TITLE
Possible error in code

### ISSUE THREAD

**Issue by borjaapaolaza** [lseman/pylspm#4]
Could you mean `data = pandas.read_csv(dados)` instead of `data = dados` line 31 of pylspm.py?

**Comment by lseman** [comment]
This version of the code considers the preprocessed data as input.

But you can use:

        if type(dados) is pd.core.frame.DataFrame:
            data = dados
        else:
            data = pd.read_csv(dados)

Laio O. Seman

**Comment by borjaapaolaza** [comment]
Thank you, Laio.
